[build]
  publish = "build"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-subfont"
  [plugins.inputs]
    inlineCss = true

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  
